version: '3'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - NODE_ENV=production

  redis:
    image: redis
    command: redis-server --requirepass localredis
    ports:
      - "6379:6379"
